### ISSUE TITLE
Support rendering bokeh plots

### ISSUE THREAD

**Issue by quantransform** [JazzCore/python-pdfkit#102]
If I embed bokeh chart by using methodology like the link below, charts won't be converted to PDF even with --javascript-delay <msec>. Is this possbile to be added?

https://bokeh.pydata.org/en/latest/docs/user_guide/embed.html

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
