### ISSUE TITLE
transform: translateY(-50%)

### ISSUE THREAD

**Issue by morganzysman** [JazzCore/python-pdfkit#104]
Hi

I'm very new to making pdf with pdfkit and wkhtmltopdf.
I have noticed that transform: translateY(-50%) doesn't seem to work is it is not positioning my image to the right place. I'm using `top: 50%; transform: translateY(-50%);`

Have you guys had this issue before ?

Regards,

Morgan
![capture d ecran 2018-05-22 a 11 37 50](https://user-images.githubusercontent.com/5576762/40354775-f4ee0728-5db4-11e8-820d-54b10e6d81a4.png)

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
