### ISSUE TITLE
OSError: wkhtmltopdf exited with non-zero code 1. error:

### ISSUE THREAD

**Issue by Yangli93** [JazzCore/python-pdfkit#106]
My python version is 3.6, wkhtmltopdf version is 0.12.5.
And the error message is empty.

**Comment by JohannesMaier** [comment]
I had the same issue, and I think this could help you: https://unix.stackexchange.com/questions/192642/wkhtmltopdf-qxcbconnection-could-not-connect-to-display

**Comment by AndronixMD** [comment]
I had the same error.
It was due to the connection of css files.

In python code i had this:
```
pdf = pdfkit.from_string(rendered, False, options=options)
```

In HTML i had this code:
```
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
```

I remove this code from in HTML template. And in python code added:
```
css = ['static/css/main.css']
pdf = pdfkit.from_string(rendered, False, options=options, css=css)
```

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
