### ISSUE TITLE
wkhtmltopdf exited with non-zero code -15. error:

### ISSUE THREAD

**Issue by rohit-taneja** [JazzCore/python-pdfkit#110]
Can you tell the meaning of exit code 15 OR When will someone get this error ?

# Software Info:

* OS : Ubuntu 14.04.3 LTS
* wkhtmltopdf : 0.12.2.1 (with patched qt)
* pdfkit : 0.6.1
* python : 3.4.3

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
