### ISSUE TITLE
Unicode Currency symbol &#8382; not displayed 

### ISSUE THREAD

**Issue by bekab95** [JazzCore/python-pdfkit#120]
I was trying to display &#8382; from string with jinja2 template but it is displayed as square

**Comment by Megha-Navsoft** [comment]
> I was trying to display ₾ from string with jinja2 template but it is displayed as square

Hi. Could you solve this error? I am getting some garbage value in the pdf before the symbol.

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...

**Comment by jorenvs** [comment]
Adding  UTF-8 meta tag to the html helped for me: https://stackoverflow.com/a/49781157/1047506

```python
pdfkit.from_string(html_str.replace('<head>', '<head><meta charset="utf-8">'), 'test.pdf')
```
