### ISSUE TITLE
page-break-* avoid not working

### ISSUE THREAD

**Issue by begonaalvarezd** [JazzCore/python-pdfkit#130]
Hello,

My concern is regarding the `page-break-* : ignore;` directives. I am trying to prevent the PDF from cutting to a new page right after a heading (among others), so the title and the content always stick together. Somehow, it really doesn't seem to work! I have tried in many different ways but the result is always the same, ignoring the CSS... any of the `page-break-inside: avoid !important;`, `page-break-after: avoid !important;` or `page-break-before: avoid !important;`seem to work. Any ideas?

Thanks!

PD: Sorry for posting this issue here. The wkhtmltopdf seems quite dead so I have decided to try here.

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
