### ISSUE TITLE
Different behaviour in Local and Server

### ISSUE THREAD

**Issue by nagarjunnas** [JazzCore/python-pdfkit#136]
I am having issue with PDFkit.

When i convert HTML to PDF and download it in local, everything is fine but in server the css is not applied correctly and texts are having spaces. I have attached two different files which is named as local and server, can you please help me with this??

[server.pdf](https://github.com/JazzCore/python-pdfkit/files/3146878/server.pdf)
[local.pdf](https://github.com/JazzCore/python-pdfkit/files/3146879/local.pdf)

**Comment by cipri-tom** [comment]
Can you have a look at the output of pdfkit on the server? Maybe the CSS files are not seen there.  In this case, there would be a warning or error

**Comment by zevaverbach** [comment]
@nagarjunnas I have a similar issue -- what OSs are your local and server running, respectively?

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
