### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by bjornasm** [JazzCore/python-pdfkit#157]
Trying to run this on a freshly updated ubuntu, with a fresh pip3 install, python 3.8. 

```
  File "/home/usrname/.local/lib/python3.8/site-packages/pdfkit/pdfkit.py", line 109, in _command
    if isinstance(self.source.source, basestring):
NameError: name 'basestring' is not defined
```

**Comment by ttrd** [comment]
I encountered the same issue. I believe that the `assert basestring` at the beginning of `pdfkit.py` is the culprit. Probably, it is not a good idea to use assert statements to distinguish between Python 2 and Python 3 because assert statements are not executed when optimization is turned on:

Without optimization (Python 3):
```
>>>python -c "assert basestring"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'basestring' is not defined
```

With optimization (Pyhton 3):
```
>>>python -Oc "assert basestring"
```
--> no exception

To fix the issue the `assert basestring`  at the beginning of pdfkit.py can be replaced by `basestring`  (without assert) for example.

**Comment by JazzCore** [comment]
Thanks for the tip, I'll remove assert in check since it should work the same without it anyway
