### ISSUE TITLE
highchart graph is not rendering 

### ISSUE THREAD

**Issue by kush99993s** [JazzCore/python-pdfkit#158]
Hello everyone,

I have disabled animation and mouse tracker for highchart, yet, I am not able to render the image. Has anyone found a solution to fix this issue?  I have also played with javascript delay to see if it renders image or not. It didn't help. 

Any help is appreciated.

From,
Kush Patel

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
