### ISSUE TITLE
Loading JS before rendering the html template 

### ISSUE THREAD

**Issue by giovabiancia** [JazzCore/python-pdfkit#160]
Hi I was trying to load my js in order to create a Chart (with chart js) before creating my pdf otherwise it does not appear.  There is any possible solution to embeed js in pdfkit ?

**Comment by juancsr** [comment]
Hi @giovabiancia did you find a way to do that? 
For me I'm waiting a few seconds (`time.sleep(5)`) before get the html using selenium.

**Comment by giovabiancia** [comment]
Nope i  rendered my chart directly from backend.

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
