### ISSUE TITLE
update pdf template but old one loading

### ISSUE THREAD

**Issue by bfate7** [JazzCore/python-pdfkit#166]
i got an issue after updating my pdf templates.... old one is loading
pdfkit version = 0.6.1
wkhtmlto pdf = 0.12.6

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
