### ISSUE TITLE
Margin option working only if all margin sare included

### ISSUE THREAD

**Issue by Scoserix** [JazzCore/python-pdfkit#185]
As the title says, try giving only 1-3 margin in the options result in this error.

Error: Currently all margin units must be the same!

example of options:

options = {
         'header-html': 'http://www.example.com/',
        'page-size': 'Letter',
        'margin-right': '0.0in',
        'margin-left': '0.0in',
        'footer-right': '[page]/[toPage]'
    }

**Comment by JazzCore** [comment]
This looks like a wkhtmltopdf issue, since pdfkit only wraps it, closing. Feel free to reopen if this is not the case, for now try running wkhtmltopdf from CLI to check whether it returns same result. You can get CLI command via class method like this:

```python
r = pdfkit.PDFKit('html', 'string', options={'page-size': 'Letter'})
' '.join(r.command())
```
Sorry that it took so long for me to get to it...
